#
# makefile for proj2, csc507/609 term 182
# author: bjr
# date: feb 2018
#

#PY= python2
PY= python3

all:
	make run-adv
	make run-prg

run-adv:
	${PY} adv-indistin.py

run-prg:
	${PY} prg-distingu.py

